import { glow } from "@/lib/staarwardd/shadow";
import { useEffect, useRef } from "react";
import { Alert, Animated, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { haptic } from "@/lib/staarwardd/haptics";

const PROMPTS = ["How are you feeling?", "What’s inspiring you right now?", "What are we making?", "Want to make something weird?", "What idea keeps coming back?"];

export function CreativityStudio({ value, onChange, onSubmit }: { value: string; onChange: (value: string) => void; onSubmit: (value?: string) => void }) {
  const spark = useRef(new Animated.Value(0)).current;
  useEffect(() => { const motion = Animated.loop(Animated.sequence([Animated.timing(spark, { toValue: 1, duration: 1600, useNativeDriver: true }), Animated.timing(spark, { toValue: 0, duration: 1600, useNativeDriver: true })])); motion.start(); return () => motion.stop(); }, [spark]);
  const scale = spark.interpolate({ inputRange: [0, 1], outputRange: [0.74, 1.34] });
  const rotate = spark.interpolate({ inputRange: [0, 1], outputRange: ["-14deg", "18deg"] });
  return <View style={styles.root}><View style={styles.canvas}><Animated.View style={[styles.spark, { transform: [{ scale }, { rotate }] }]}><Text style={styles.sparkMark}>✦</Text></Animated.View><View style={styles.paint} /><View style={styles.photo} /><View style={styles.paper}><Text style={styles.paperMark}>…</Text></View><View style={styles.thread} /><Text style={styles.canvasLabel}>MATERIAL IS GATHERING</Text></View><Text style={styles.title}>What are we making?</Text><Text style={styles.detail}>Speak, type, or begin with a fragment.</Text><View style={styles.prompts}>{PROMPTS.map((prompt) => <Pressable key={prompt} accessibilityRole="button" onPress={() => onSubmit(prompt)} style={({ pressed }) => [styles.prompt, pressed && styles.pressed]}><Text style={styles.promptText}>{prompt}</Text></Pressable>)}</View><View style={styles.inputShell}><TextInput value={value} onChangeText={onChange} onSubmitEditing={() => onSubmit()} returnKeyType="done" placeholder="A color, a feeling, an unfinished thought…" placeholderTextColor="#A4A5C5" style={styles.input} multiline maxLength={240} /><View style={styles.inputActions}><Pressable accessibilityRole="button" onPress={() => Alert.alert("Voice response", "Voice response requires a connected transcription service. You can type your answer and hear the Guardian through the optional device voice control.")} style={({ pressed }) => [styles.voice, pressed && styles.pressed]}><Text style={styles.voiceText}>VOICE</Text></Pressable><Pressable accessibilityRole="button" onPress={() => { haptic.light(); onSubmit(); }} style={({ pressed }) => [styles.open, pressed && styles.pressed]}><Text style={styles.openText}>OPEN IDEA</Text><Text style={styles.arrow}>→</Text></Pressable></View></View></View>;
}

const styles = StyleSheet.create({ root: { marginTop: 16 }, canvas: { height: 190, borderRadius: 21, overflow: "hidden", backgroundColor: "rgba(31,17,68,0.66)", borderWidth: 1, borderColor: "rgba(204,164,255,0.34)", justifyContent: "center", alignItems: "center" }, spark: { width: 72, height: 72, borderRadius: 36, backgroundColor: "rgba(244,196,89,0.22)", alignItems: "center", justifyContent: "center", ...glow("#F4C459", 18, 0.9) }, sparkMark: { color: "#FFE09A", fontSize: 34 }, paint: { position: "absolute", width: 108, height: 42, borderRadius: 99, backgroundColor: "rgba(242,95,188,0.38)", transform: [{ rotate: "-19deg" }], left: -8, top: 40 }, photo: { position: "absolute", width: 73, height: 94, borderRadius: 5, borderWidth: 3, borderColor: "rgba(123,220,255,0.68)", right: 19, top: 21, transform: [{ rotate: "12deg" }] }, paper: { position: "absolute", width: 78, height: 51, borderRadius: 4, backgroundColor: "rgba(255,242,211,0.83)", left: 28, bottom: 20, transform: [{ rotate: "-8deg" }], justifyContent: "center", alignItems: "center" }, paperMark: { color: "#453D68", fontSize: 28 }, thread: { position: "absolute", width: 112, height: 2, backgroundColor: "#6DE6D5", transform: [{ rotate: "-32deg" }], right: 5, bottom: 26 }, canvasLabel: { position: "absolute", bottom: 13, color: "#F0DCFF", fontSize: 9, letterSpacing: 1.1, fontWeight: "800" }, title: { color: "#F4F7FF", fontSize: 20, fontWeight: "800", marginTop: 17 }, detail: { color: "#C7C7E4", fontSize: 12, lineHeight: 17, marginTop: 4 }, prompts: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 12 }, prompt: { minHeight: 34, borderRadius: 11, paddingHorizontal: 10, justifyContent: "center", borderWidth: 1, borderColor: "rgba(218,193,255,0.24)", backgroundColor: "rgba(34,21,74,0.54)" }, promptText: { color: "#E2D7FF", fontSize: 10, fontWeight: "700" }, inputShell: { marginTop: 14, borderRadius: 18, padding: 13, backgroundColor: "rgba(10,14,37,0.71)", borderWidth: 1, borderColor: "rgba(218,193,255,0.2)" }, input: { color: "#F3F4FF", minHeight: 60, textAlignVertical: "top", fontSize: 14, lineHeight: 20, paddingHorizontal: 0, paddingTop: 0 }, inputActions: { flexDirection: "row", gap: 8, marginTop: 7 }, voice: { minHeight: 42, paddingHorizontal: 13, borderRadius: 12, borderWidth: 1, borderColor: "rgba(226,236,255,0.22)", justifyContent: "center" }, voiceText: { color: "#D8E1F5", fontSize: 10, letterSpacing: 0.7, fontWeight: "800" }, open: { flex: 1, minHeight: 42, paddingHorizontal: 13, borderRadius: 12, backgroundColor: "#D8B0FF", flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, openText: { color: "#211436", fontSize: 10, letterSpacing: 0.65, fontWeight: "800" }, arrow: { color: "#211436", fontSize: 18 }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] } });
