import AsyncStorage from "@react-native-async-storage/async-storage";
import { useVideoPlayer, VideoView } from "expo-video";
import { useEffect, useRef, useState } from "react";
import { AccessibilityInfo, Platform, Pressable, StyleSheet, Text, View, useWindowDimensions } from "react-native";
import { glow } from "@/lib/staarwardd/shadow";
import { useStaarAudio } from "@/lib/staarwardd/audio-provider";

const LAUNCH_KEY="staarwardd.launch-seen"; const isWeb=Platform.OS==="web";
const WEB_MP4="/video/guardian-toronto-traverse-hd.mp4",WEB_WEBM="/video/guardian-toronto-traverse-hd.webm",WEB_POSTER="/video/guardian-toronto-traverse-poster.jpg";
const NATIVE_SRC=require("@/assets/videos/guardian-toronto-traverse-hd.mp4");
export type PortalId="creativity"|"work"|"home"|"wellbeing"|"relationships"|"events"|"style";
export function useReturningUser(){const[loading,setLoading]=useState(true),[returning,setReturning]=useState(false);useEffect(()=>{AsyncStorage.getItem(LAUNCH_KEY).then(v=>{setReturning(v==="1");setLoading(false)});},[]);return{loading,returning,markSeen:()=>void AsyncStorage.setItem(LAUNCH_KEY,"1")};}
const PORTALS:any[]=[{id:"creativity",label:"Creativity",img:require("@/assets/images/staarwardd/portal-creativity-v7.webp")},{id:"work",label:"Work",img:require("@/assets/images/staarwardd/portal-work-v7.webp")},{id:"home",label:"Home",img:require("@/assets/images/staarwardd/portal-home-v7.webp")},{id:"wellbeing",label:"Wellbeing",img:require("@/assets/images/staarwardd/portal-wellbeing-v7.webp")},{id:"relationships",label:"Relationships",img:require("@/assets/images/staarwardd/portal-relationships-v7.webp")},{id:"events",label:"Community",img:require("@/assets/images/staarwardd/portal-community-v7.webp")},{id:"style",label:"Style",img:require("@/assets/images/staarwardd/portal-style-v7.webp")}];
const RNW=isWeb?require("react-native-web"):null;
export function LaunchSequence({onComplete}:{onComplete:()=>void;onSelectPortal?:(id:PortalId)=>void}){
 const{width}=useWindowDimensions(),desktop=width>=700,audio=useStaarAudio();const[started,setStarted]=useState(false),[ready,setReady]=useState(!isWeb),[portalCount,setPortalCount]=useState(0),[reduced,setReduced]=useState(false);const videoRef=useRef<any>(null),done=useRef(false),timer=useRef<any>(null),cueStage=useRef(-1);const nativePlayer=useVideoPlayer(isWeb?null:NATIVE_SRC,p=>{p.loop=false;p.muted=false;});
 const finish=()=>{if(done.current)return;done.current=true;if(timer.current)clearInterval(timer.current);try{isWeb?videoRef.current?.pause?.():nativePlayer.pause()}catch{}audio.stopAll();onComplete();};
 useEffect(()=>{AccessibilityInfo.isReduceMotionEnabled?.().then(v=>setReduced(!!v)).catch(()=>{});return()=>{if(timer.current)clearInterval(timer.current)};},[]);useEffect(()=>{if(!reduced)return;const t=setTimeout(finish,1800);return()=>clearTimeout(t);},[reduced]);
 useEffect(()=>{if(!started)return;timer.current=setInterval(()=>{let t=0,d=0;try{if(isWeb){const v=videoRef.current;if(!v)return;t=v.currentTime||0;d=v.duration||0;if(v.ended){finish();return}}else{t=nativePlayer.currentTime||0;d=nativePlayer.duration||0;if(d>0&&t>=d-.1){finish();return}}}catch{return}if(d<=0)return;const pct=t/d;let stage=0;if(pct>=.12)stage=1;if(pct>=.34)stage=2;if(pct>=.58)stage=3;if(pct>=.76)stage=4;if(pct>=.86)stage=5;if(stage!==cueStage.current){cueStage.current=stage;const cues:any[]=["opening","flight","traverse","storm","shield","portal"];audio.playCue(cues[stage]);}const r=Math.max(d-8,0);setPortalCount(n=>Math.max(n,t<r?0:Math.min(7,Math.floor((t-r)/.95)+1)));},180);return()=>clearInterval(timer.current);},[started,audio]);
 const start=()=>{if(started)return;audio.update({master:true,music:true,ambience:true,volume:.34});setStarted(true);cueStage.current=-1;try{if(isWeb){const v=videoRef.current;if(!v){setStarted(false);return}v.currentTime=0;v.muted=true;const p=v.play?.();audio.playCue("opening");cueStage.current=0;p?.catch?.(()=>setStarted(false));}else{nativePlayer.currentTime=0;nativePlayer.muted=false;nativePlayer.volume=1;nativePlayer.play();audio.playCue("opening");cueStage.current=0;}}catch{setStarted(false)}};
 const stage=desktop?{width:Math.min(width*.52,620),alignSelf:"center" as const}:null;
 return <View style={s.root}><View style={[s.stage,stage]}>{isWeb?RNW.unstable_createElement("video",{ref:videoRef,playsInline:true,preload:"metadata",poster:WEB_POSTER,muted:true,onCanPlay:()=>setReady(true),onLoadedData:()=>setReady(true),onLoadedMetadata:()=>setReady(true),onEnded:finish,onError:()=>setReady(true),style:{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:desktop?"contain":"cover",background:"#000",transform:"translateZ(0)",imageRendering:"auto"},children:[RNW.unstable_createElement("source",{key:"mp4",src:WEB_MP4,type:"video/mp4"}),RNW.unstable_createElement("source",{key:"webm",src:WEB_WEBM,type:"video/webm"})]}):<VideoView player={nativePlayer} style={StyleSheet.absoluteFill} contentFit={desktop?"contain":"cover"} nativeControls={false}/>}</View>
 {!started&&!reduced&&<View style={s.gate}><Text style={s.kicker}>STAARWAARDD · TORONTO</Text><Text style={s.title}>The Guardian is ready.</Text><Text style={s.note}>{ready?"Cinematic ready. Enter with full Guardian sound.":"Cinematic is connecting — you can enter now."}</Text><Pressable onPress={start} style={s.enter}><Text style={s.enterText}>ENTER STAARWAARDD · SOUND ON</Text></Pressable></View>}
 {portalCount>0&&<View style={s.portalRow}>{PORTALS.slice(0,portalCount).map((p:any)=><View key={p.id} style={s.portal}>{isWeb&&RNW.unstable_createElement("img",{src:p.img?.uri??p.img,style:{width:54,height:54,borderRadius:12,objectFit:"cover"}})}{!isWeb&&<NativeImage img={p.img}/>}<Text style={s.portalLabel}>{p.label}</Text></View>)}</View>}</View>;
}
function NativeImage({img}:{img:any}){const{Image}=require("react-native");return <Image source={img} style={{width:54,height:54,borderRadius:12}}/>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#000",overflow:"hidden"},stage:{flex:1,width:"100%",backgroundColor:"#000",overflow:"hidden"},gate:{...StyleSheet.absoluteFillObject,zIndex:20,alignItems:"center",justifyContent:"center",padding:24,backgroundColor:"rgba(1,4,12,.58)"},kicker:{color:"#E8C86F",fontSize:10,letterSpacing:2.2,fontWeight:"900"},title:{color:"#FFF",fontSize:28,lineHeight:34,textAlign:"center",fontWeight:"900",marginTop:9},note:{color:"#D8E3F5",fontSize:13,lineHeight:19,textAlign:"center",marginTop:7},enter:{minHeight:52,marginTop:20,paddingHorizontal:22,borderRadius:999,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"#F2D980",backgroundColor:"rgba(232,200,111,.18)",...glow("#E8C86F",22,.55)},enterText:{color:"#FFF2B8",fontSize:11,letterSpacing:1.25,fontWeight:"900"},portalRow:{position:"absolute",bottom:86,left:12,right:12,flexDirection:"row",flexWrap:"wrap",justifyContent:"center",gap:8,pointerEvents:"none"},portal:{alignItems:"center",padding:6,borderRadius:14,backgroundColor:"rgba(4,7,16,.62)",borderWidth:1,borderColor:"rgba(232,200,111,.72)",...glow("#7EDCF3",14,.8)},portalLabel:{color:"#F4F7FF",fontSize:9,fontWeight:"800",letterSpacing:.4,marginTop:3}});