import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { useGuardianActivity } from "@/lib/staarwardd/guardian-activity";

export function GuardianActivitySheet({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { ready, receipts, erase } = useGuardianActivity();
  return <Modal transparent visible={open} animationType="slide" onRequestClose={onClose}><View style={styles.back}><View style={styles.sheet}><ScrollView showsVerticalScrollIndicator={false}><Text style={styles.kicker}>GUARDIAN ACTIVITY</Text><Text style={styles.title}>Visible local receipts.</Text><Text style={styles.copy}>Each entry states the trigger, requested action, approval state, and outcome. History persists only when Local Memory and receipt history are both enabled. It never proves an external action occurred.</Text>{!ready ? <Text style={styles.muted}>Loading local activity…</Text> : receipts.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>No activity receipts yet.</Text><Text style={styles.emptyCopy}>Prepared, unavailable, denied, failed, and supported local outcomes will appear here as you use Guardian.</Text></View> : <View style={styles.list}>{receipts.map((receipt) => <View key={receipt.id} style={styles.receipt}><View style={styles.receiptHeader}><Text style={styles.outcome}>{receipt.outcome.replace(/-/g, " ").toUpperCase()}</Text><Text style={styles.persistence}>{receipt.persisted ? "SAVED LOCALLY" : "SESSION ONLY"}</Text></View><Text style={styles.action}>{receipt.requestedAction}</Text><Text style={styles.detail}>Trigger: {receipt.trigger}</Text><Text style={styles.detail}>Reason: {receipt.reason}</Text><Text style={styles.detail}>Approval: {receipt.approvalState.replace(/-/g, " ")} · Source: {receipt.source}</Text><Text style={styles.time}>{new Date(receipt.time).toLocaleString()}</Text></View>)}</View>}<Pressable accessibilityRole="button" accessibilityLabel="Erase all Guardian activity history" onPress={erase} style={({ pressed }) => [styles.erase, pressed && styles.pressed]}><Text style={styles.eraseText}>ERASE ACTIVITY HISTORY</Text></Pressable></ScrollView><Pressable accessibilityRole="button" accessibilityLabel="Close Guardian activity history" onPress={onClose} style={({ pressed }) => [styles.close, pressed && styles.pressed]}><Text style={styles.closeText}>CLOSE</Text></Pressable></View></View></Modal>;
}

const styles = StyleSheet.create({
  back: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(2,5,12,0.8)", padding: 14 }, sheet: { maxHeight: "86%", backgroundColor: "#101B31", borderRadius: 25, padding: 21, borderWidth: 1, borderColor: "rgba(232,200,111,0.3)" }, kicker: { color: "#E8C86F", fontSize: 10, letterSpacing: 1.3, fontWeight: "800" }, title: { color: "#F4F7FF", fontSize: 23, fontWeight: "800", marginTop: 7 }, copy: { color: "#C3CEE0", fontSize: 13, lineHeight: 20, marginTop: 9 }, muted: { color: "#AAB7CD", marginTop: 22 }, empty: { marginTop: 18, borderLeftWidth: 2, borderLeftColor: "#E8C86F", backgroundColor: "rgba(232,200,111,0.08)", padding: 13, borderRadius: 10 }, emptyTitle: { color: "#F1D985", fontSize: 12, fontWeight: "800" }, emptyCopy: { color: "#C6D0E0", fontSize: 11, lineHeight: 16, marginTop: 3 }, list: { gap: 9, marginTop: 16 }, receipt: { borderRadius: 15, padding: 13, backgroundColor: "rgba(7,13,28,0.58)", borderWidth: 1, borderColor: "rgba(220,230,255,0.12)" }, receiptHeader: { flexDirection: "row", justifyContent: "space-between", gap: 8 }, outcome: { color: "#E8C86F", fontSize: 9, fontWeight: "800", letterSpacing: 0.9 }, persistence: { color: "#90A4C7", fontSize: 8, fontWeight: "800", letterSpacing: 0.75 }, action: { color: "#EDF4FF", fontSize: 14, lineHeight: 19, fontWeight: "800", marginTop: 6 }, detail: { color: "#BAC7DB", fontSize: 10, lineHeight: 15, marginTop: 3 }, time: { color: "#7E91B1", fontSize: 9, marginTop: 7 }, erase: { minHeight: 46, marginTop: 17, borderRadius: 14, borderWidth: 1, borderColor: "rgba(240,128,155,0.42)", alignItems: "center", justifyContent: "center" }, eraseText: { color: "#F4A6B8", fontSize: 10, letterSpacing: 0.7, fontWeight: "800" }, close: { minHeight: 45, justifyContent: "center", alignItems: "center", marginTop: 8 }, closeText: { color: "#BAC6DD", fontSize: 11, letterSpacing: 0.9, fontWeight: "800" }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] },
});
