import type { DimensionProfile, PortalId } from "./types";

export type PortalMeta = Omit<DimensionProfile, "image">;

export const PORTAL_META: PortalMeta[] = [
  { id: "creativity", name: "Creativity", glyph: "✦", color: "#8B5CF6", accent: "#D8C5FF", eyebrow: "MAKE SPACE FOR THE IDEA", promise: "Inspire · Imagine · Create", aiRole: "A creative partner for shaping momentum, drafts, and constraints.", privacyCue: "Private thoughts stay within this preview on this device.", defaultMode: "Create", focus: "Move one living idea toward expression.", starterActions: ["Create a 45-minute ritual", "Turn ideas into one project", "Protect rest beside the work"], tools: ["Idea distiller", "Creative ritual", "Finish-line builder"], promptSeed: "Help me move a creative idea forward" },
  { id: "work", name: "Work", glyph: "▥", color: "#4AA7FF", accent: "#C4E5FF", eyebrow: "CLARITY FOR THE WORKDAY", promise: "Focus · Grow · Achieve", aiRole: "A strategic operator for priorities, plans, and prepared work.", privacyCue: "Prepared work remains a preview until you explicitly approve it elsewhere.", defaultMode: "Plan", focus: "Choose the highest-leverage next step.", starterActions: ["Build a realistic focus day", "Prepare a client deliverable", "Protect deep work"], tools: ["Priority triage", "Deep-work shield", "Deliverable builder"], promptSeed: "Help me plan my work priorities" },
  { id: "home", name: "Home", glyph: "⌂", color: "#E8A560", accent: "#FFE0B8", eyebrow: "MAKE HOME FEEL LIGHTER", promise: "Comfort · Harmony · Sanctuary", aiRole: "A calm home steward for routines, spaces, and household rhythm.", privacyCue: "No devices are controlled from this preview.", defaultMode: "Coach", focus: "Create visible calm in one useful place.", starterActions: ["Create a gentle home reset", "Plan food and cleanup", "Organize this week"], tools: ["Room reset", "Meal rhythm", "Household sequence"], promptSeed: "Help me create a gentle home reset" },
  { id: "wellbeing", name: "Wellbeing", glyph: "◉", color: "#50D5B7", accent: "#B8F5E7", eyebrow: "A KINDER ENERGY FLOOR", promise: "Restore · Balance · Thrive", aiRole: "A supportive guide for practical rhythms, not medical advice.", privacyCue: "This preview does not diagnose, treat, or store health information.", defaultMode: "Listen", focus: "Regulate before optimizing the day.", starterActions: ["Restore energy today", "Plan movement and rest", "Make a low-stress rhythm"], tools: ["Energy check", "Recovery rhythm", "Movement plan"], promptSeed: "Help me restore my energy today" },
  { id: "relationships", name: "Relationships", glyph: "∞", color: "#EF8EA8", accent: "#FFD1DC", eyebrow: "RELATE WITH INTENTION", promise: "Connect · Love · Support", aiRole: "A communication coach for connection, boundaries, and preparation.", privacyCue: "Messages are drafts only; sending always remains under your control.", defaultMode: "Coach", focus: "Name the real connection need before reacting.", starterActions: ["Reconnect in my own voice", "Prepare a kind boundary", "Plan family time"], tools: ["Connection compass", "Boundary rehearsal", "Message studio"], promptSeed: "Help me prepare a thoughtful relationship next step" },
  { id: "events", name: "Community", glyph: "◇", color: "#E8C86F", accent: "#FFF0B7", eyebrow: "MAKE SPACE FOR WHAT MATTERS", promise: "Gather · Plan · Arrive", aiRole: "An event planner for grounded options, timing, and prepared outreach.", privacyCue: "Invites, bookings, registrations, and messages are never sent from this preview.", defaultMode: "Plan", focus: "Coordinate a meaningful event without overcommitting.", starterActions: ["Compare event options", "Plan a gathering", "Prepare an outreach draft"], tools: ["Event map", "Energy budget", "Outreach planner"], promptSeed: "Help me plan an event that fits my energy" },
  { id: "style", name: "Style", glyph: "△", color: "#C9824A", accent: "#FFD1A8", eyebrow: "EXPRESS WITH INTENTION", promise: "Express · Elevate · Empower", aiRole: "A personal curator for looks, wardrobe decisions, and context.", privacyCue: "Recommendations are suggestions; this preview never purchases on your behalf.", defaultMode: "Create", focus: "Build a complete expression from what you already own.", starterActions: ["Build an outfit formula", "Prepare a weather-aware look", "Edit the wardrobe"], tools: ["Outfit studio", "Wardrobe edit", "Event-ready plan"], promptSeed: "Help me build an outfit from what I own" },
];

export const PORTAL_META_BY_ID = Object.fromEntries(PORTAL_META.map((portal) => [portal.id, portal])) as Record<PortalId, PortalMeta>;
